version: '3.3'

services:
  db:
    image: mysql:5.6.40
    environment:
      MYSQL_DATABASE: 'flickball'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'flickball'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'flickball'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted