# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
#      - run:
#          name: Login to DockerHub
#          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mkdir ~/.aws
      - run: printf "[default]\nregion = ap-southeast-1\n" > ~/.aws/config
      - run: printf "[ecr-push-user]\naws_access_key_id = AKIA24VDTQOYNXFWDG4Y\naws_secret_access_key = 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\n" > ~/.aws/credentials
      - run: cat ~/.aws/credentials

      # run tests!
      # - run: mvn clean package

      # build and push docker image to docker hub
      # - run: mvn clean compile jib:build
      - run: mvn clean compile jib:dockerBuild -Djib.to.image=748741166000.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo/circleci-test:$CIRCLE_BUILD_NUM
      - run: AWS_PROFILE=ecr-push-user docker push 748741166000.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo/circleci-test:$CIRCLE_BUILD_NUM

      - store_artifacts:
          path: ~/repo/target/circleci-test-0.0.1-SNAPSHOT.jar
          destination: circleci-test.jar
