# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@4.0.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image: