version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@4.0.0

workflows:
  version: 2
  build_push:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}
          attach-workspace: true
          requires:
            - build

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/workspace

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean package
      - run: ls -al

      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .
